api:
  port: 3000
  secret:
zendesk:
  username:
  token:
  remoteUri: https://lostmyname.zendesk.com/api/v2
tags:
  585052: facebook-english
  585072: facebook-spanish
  585042: facebook-german
  585082: facebook-french
